import { LeadActivityDto } from './LeadActivityDto';

export interface LeadDto {
  id: string;
  leadNumber?: string | null;
  tenantId: string;
  firstName?: string | null;
  lastName?: string | null;
  fullName?: string | null;
  email?: string | null;
  phone?: string | null;
  mobilePhone?: string | null;
  companyName?: string | null;
  jobTitle?: string | null;
  website?: string | null;
  addressStreet?: string | null;
  addressCity?: string | null;
  addressState?: string | null;
  addressPostalCode?: string | null;
  addressCountry?: string | null;
  fullAddress?: string | null;
  status?: string | null;
  statusChangedDate: string;
  rating?: string | null;
  leadScore: number;
  source?: string | null;
  estimatedValue?: number | null;
  estimatedCloseDate?: string | null;
  probability: number;
  industry?: string | null;
  companySize?: string | null;
  annualRevenue?: number | null;
  ownerId?: string | null;
  ownerName?: string | null;
  ownerEmail?: string | null;
  assignedDate?: string | null;
  campaignName?: string | null;
  referralSource?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmContent?: string | null;
  utmTerm?: string | null;
  isConverted: boolean;
  convertedDate?: string | null;
  convertedAccountId?: string | null;
  convertedAccountName?: string | null;
  convertedOpportunityId?: string | null;
  convertedOpportunityValue?: number | null;
  lastContactedDate?: string | null;
  lastActivityDate?: string | null;
  lastActivityType?: string | null;
  lastActivityNotes?: string | null;
  nextFollowUpDate?: string | null;
  totalActivitiesCount: number;
  totalCallsCount: number;
  totalEmailsCount: number;
  totalMeetingsCount: number;
  description?: string | null;
  requirements?: string | null;
  disqualificationReason?: string | null;
  internalNotes?: string | null;
  doNotCall: boolean;
  doNotEmail: boolean;
  optedOutOfMarketing: boolean;
  preferredContactMethod?: string | null;
  preferredContactTime?: string | null;
  createdDate: string;
  createdBy?: string | null;
  createdByName?: string | null;
  modifiedDate: string;
  modifiedBy?: string | null;
  modifiedByName?: string | null;
  isDeleted: boolean;
  deletedDate?: string | null;
  deletedBy?: string | null;
  tags?: string | null;
  activities?: LeadActivityDto[] | null;
}
